name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Use the appropriate Ruby version for your Jekyll setup

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./ # Change this to the correct source directory
          destination: ./_site
          future: false
          build_revision: ${{ github.sha }}
          verbose: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
